### ISSUE TITLE
Move base types to a standalone library as foundation of georust libraries

### ISSUE THREAD

**Issue by sunng87** [georust/rust-wkt#12]
(Greetings, I just joined georust on @frewsxcv 's invitation)

Since we have a clear road map for geo-spatial libraries in rust, I suggest that the first step is to move all standard types into a standalone library. We can call it `geo-types`. It will contain all types described in OGC Simple Feature standard. Our I/O libraries like wkt and geojson will depend on it, and our future libraries will also use types defined in this library. This will make it consistent from user.

**Comment by mgax** [comment]
That's what https://github.com/georust/rust-geo/issues/2 is about.

**Comment by sunng87** [comment]
oh, didn't notice that is already in progress. I will close this one.
