### ISSUE TITLE
Public interface for converting str -> Wkt / Geo?

### ISSUE THREAD

**Issue by gnidan** [georust/rust-wkt#25]
Pardon me because I am just learning Rust, but how do you convert a WKT string to a georust Geo? `Wkt::from_str` is private -- am I missing something?

Thanks!

**Comment by frewsxcv** [comment]
There is unfortunately no way to do this currently. I'll try to fix this over the next few days.

**Comment by frewsxcv** [comment]
Made them public in https://github.com/georust/rust-wkt/pull/29

**Comment by TeXitoi** [comment]
Fixed by #29
